### ISSUE TITLE
Crea un archivo nuevo periodicos.js

### ISSUE THREAD

**Issue by yesthatguy** [devfmx/exechacker-2017nov-thenest#4]
Usando el sintaxis de Javascript, el archivo debe de tener un arreglo "periodicos" que tiene nombres de periodicos, y un loop/bucle que imprime los nombres a la consola.

Puedes comprobar tu código copiando y pegando en la consola de Chrome o jsbin.com

**Comment by carlosromano** [comment]
Listo!
